-- Active: 1668065856987@@127.0.0.1@3306
DROP SCHEMA IF EXISTS `project`;

CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8;
USE `project`;

CREATE TABLE consumer ---下单用户
(C_ID   INT AUTO_INCREMENT,
FIRST_NAME  VARCHAR(20),
LAST_NAME   VARCHAR(20),
PHONE_NUMBER VARCHAR(20),
PROVINCE   VARCHAR(25),
STREET_ADDRESS VARCHAR(40),
PRIMARY KEY(C_ID));

CREATE TABLE merchant ---商家
(M_ID   INT,
M_NAME VARCHAR(20),
M_PROVINCE VARCHAR(25),
M_STREET_ADDRESS VARCHAR(40),
COMSUPTION_PP INT, ---人均消费
RANK DEC(1,1), ---评分
NUMBER_COMMENTS INT,---评论数
NUMBER_DISCOUNT INT,---套餐数量
PRIMARY KEY(M_ID));

CREATE TABLE food --- 商品
(F_ID  INT,
F_NAME VARCHAR(20),
PRICE DEC(6,2),
M_ID INT,
PRIMARY KEY(F_ID),
FOREIGN KEY(M_ID) REFERENCES merchant(M_ID));

CREATE TABLE order ---订单
(O_ID INT,
C_ID INT,
F_ID INT,
BILL DEC(10,2),
PRIMARY KEY(O_ID),
FOREIGN KEY(C_ID) REFERENCES consumer(C_ID),
FOREIGN KEY(F_ID) REFERENCES food(F_ID));

