-- Active: 1668065856987@@127.0.0.1@3306
DROP SCHEMA IF EXISTS `project`;

CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8;
USE `project`;

CREATE TABLE consumer
(C_ID   INT AUTO_INCREMENT,
FIRST_NAME  VARCHAR(20),
LAST_NAME   VARCHAR(20),
PHONE_NUMBER VARCHAR(20),
PROVINCE   VARCHAR(25),
STREET_ADDRESS VARCHAR(40),
PRIMARY KEY(C_ID));

CREATE TABLE merchant
(M_ID   INT,
M_NAME VARCHAR(20),
M_PROVINCE VARCHAR(25),
M_STREET_ADDRESS VARCHAR(40),
COMSUPTION_PP INT,
RANK INT,
NUMBER_COMMENTS INT,
NUMBER_DISCOUNT INT,
PRIMARY KEY(M_ID));

CREATE TABLE food
(F_ID  INT,
F_NAME VARCHAR(20),
PRICE DEC(6,2),
M_ID INT,
PRIMARY KEY(F_ID),
FOREIGN KEY(M_ID) REFERENCES merchant(M_ID));

CREATE TABLE order
(O_ID INT,
C_ID INT,
F_ID INT,
BILL DEC(10,2),
PRIMARY KEY(O_ID),
FOREIGN KEY(C_ID) REFERENCES consumer(C_ID),
FOREIGN KEY(F_ID) REFERENCES food(F_ID));

